### ISSUE TITLE
Automated Calculation of Time-Average and Standard-Deviation within Timeframe

### ISSUE THREAD

**Issue by DnnsSrlnd** [SiLab-Bonn/irrad_control#24]
An automated calculation of the time-average and standard deviation of all selected channels within the displayed timeframe would be nice.

**Comment by leloup314** [comment]
This is about to go into the development branch, thanks :+1: Once it's in master I will close this

**Comment by leloup314** [comment]
@DnnsSrlnd do I remember correctly that the graphs in the scrolling data plots are now to thin for good visuals?

**Comment by DnnsSrlnd** [comment]
Yes, their are either too thin or now have a transparent feature but I would suspect the first.

**Comment by leloup314** [comment]
It's a mixture of both ;) I will change this

**Comment by leloup314** [comment]
I changed the behavior of the stats "window". See df4a908ddf67746f57cf716d27893321e32a77a6. Should be better now

**Comment by leloup314** [comment]
Added statistics for all plots in 814d288aa8275d8de1a068185c93fdb4e9574ef4

**Comment by leloup314** [comment]
Close in favor of #35
