### ISSUE TITLE
Workflow Enhancement: Record Button

### ISSUE THREAD

**Issue by DnnsSrlnd** [SiLab-Bonn/irrad_control#25]
To increase the efficiency during measurements it would be nice to have a small "Rec"-toggle-button somewhere on the GUI of the raw data visualisation (maybe on the beam parameter visualization too) to toggle between the data recording and non recording status.

**Comment by leloup314** [comment]
Agreed! I will implement this in a way, that it has to be enabled through the control menu once to make sure the user knows what's going on ;)

**Comment by leloup314** [comment]
Close in favor of #35
