### ISSUE TITLE
Clean-up of `rad_monitor` branch

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/irrad_control#45]
@christian235 please clean up the redundant files in the `rad_monitor` branch so the folder structure looks like this:

- rad_monitor:
    -> `__init__.py` 
    -> iseg_hv.py
    -> arduino_freq_counter.py
    
     - ArduinoFreqCount: 
         -> ArduinoFreqCounter.ino

        - FreqCounter:
            -> `The files of the FreqCounter library` (utils, examples, ...)

Also, make sure to test and comment ;)

**Comment by christian235** [comment]
I have a folder called  "__pycache__" (__ __). Normally I would delte this one but in this case with the double underscore I'm kind of confused. Can I delete this kind of backup or is it necessary for anything?

**Comment by leloup314** [comment]
You can delete it, simply ignore it or explicitly add it to the `.gitignore`-file in order to have `git` ignore it. More info [here](https://stackoverflow.com/questions/16869024/what-is-pycache)

**Comment by christian235** [comment]
Finally i tested all functions and now everything is working correct. So you can start to include rad_monitor.

**Comment by leloup314** [comment]
Looks fine. Can you still add the missing FreqCount library files into the `ArduinoFreqCount` folder?

**Comment by christian235** [comment]
Sorry for the merge. I forgot that Ihad previous changes. Im not sure if we need the folder 'advance' but just for the case I also included this one.

**Comment by leloup314** [comment]
I just pushed what I wanted. Now it looks like in the description above

**Comment by leloup314** [comment]
Closed with #49
